---
language: python
services: docker

env:
  global:
    - MOLECULE_PROJECT_DIR: "$TRAVIS_BUILD_DIR"
    - MOLECULE_ROLE_NAME: "$(basename $TRAVIS_BUILD_DIR)"

before_script:
  - wget https://raw.githubusercontent.com/nl2go/docker-molecule/1.0.5/docker-compose.yml
  - docker-compose up -d

script:
  - docker-compose exec molecule molecule test --all

after_script:
  - docker-compose down

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
