---
language: python
services: docker

env:
  global:
    - MOLECULE_PROJECT_DIR: "$TRAVIS_BUILD_DIR"
    - MOLECULE_ROLE_NAME: "$(basename $TRAVIS_BUILD_DIR)"

before_script:
  - wget https://raw.githubusercontent.com/nl2go/docker-molecule/2.22-n2g-1.0.0/docker-compose.yml
  - docker-compose up -d
  - pip install ansible coverage codecov ansible-filter==1.0.0

script:
  - docker-compose exec molecule molecule test --all
  - coverage run --source=filter_plugins -m unittest discover filter_plugins/tests

after_script:
  - docker-compose down
  - codecov

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
